## TensorFlow

- Tensorflow는 구글 브레인에서 개발
- 현재 구글의 연구와 프로덕션 모두에서 활발하게 사용
- 2.x로 오면서 많은 것이 편리하게 변화
- Tensorflow.js의 릴리즈
  - 브라우저에서 파이썬 모델을 돌릴 수 있게 됨
  - 자바스크립트만으로도 돌릴 수 있게됨
- Tensorflow Lite의 릴리즈
  - 모바일 및 임베디드 기기에서 동작할 수 있게 함
- Tensorflow Extended (TFX)의 릴리즈
  - ML pipeline을 위한 end-to-end 플랫폼
  - 유지보수, 모듈화 등에 큰 도움이 됨
- TensorFlow는 머신러닝을 위한 엔드 투 엔드 오픈소스 플랫폼
- 도구, 라이브러리, 커뮤니티 리소스로 구성된 포괄적이고 유연한 생태계


## TF vs Theano vs Torch (초기 기준)

### TF

- 테아노와 유사하게 네트워크 기반의 심볼릭 그래피르르 사용
- 파이썬과 C/C++ 모두 사용이 가능하지만 주력은 파이썬
- 텐소보드(TensorBoard)를 통해 비주얼라이제이션을 지원
- 단점: 성능상, 그리고 테아노의 scan같은 네트워크에 있는 심볼릭들을 루핑(loop)할 수 있는 기능 X

### 테아노

- 심볼릭 텐서 그래프를 사용하는 최초의 프레임워크로 토치 같은 프레임워크보다 유연
- 테아노를 기반으로 하는 고수준 프레임워크들도 존재하고 있고 텐서플로우나 토치에서는 지원되지 않는 윈도우즈 환경에서도 사용 가능
- 반면 텐서플로우에는 없는 컴파일 프로세스로 인한 오버헤드가 단점
- 파이썬 모듀을 로딩하는 impoirt theano 명령이 느리고 확장이나 개선이 어려운 복잡한 구조

### 토치

- 토치는 컨볼루션(합성곱 신경망) 부분에서 좋은 성능을 보이고 있고 여러가지 컨볼루션 알고리즘을 구현

## PyTorch

- 딥러닝 알고리즘이 가지는 많은 연산량 무제 해결을 위해 GPU를 사용하여 행렬연산을 가속하는 테아노라는 딥러닝 프레임워크가 개발
- 이후 케라스 같은 오픈소스 라이브러리들이 테아노를 기반으로 탄생
- 직관적이지 않은 사용법과 잦은 버그, 대형 모델에 적용하기 어려운 점으로 개발 중단
- 텐서플로우, 카페, MXNet, CNTK의 발전이 활성화
- 2017년 초에 공개된 딥러닝 프레임워크로 개발자들과 연구자들이 쉽게 GPU를 활용하여 인공 신경망 모델을 만들고 학습시킬 수 있게 도와줌
- 파이토치의 전신이라고 할 수 있는 토치(torch)는 루아 프로그래밍 언어로 되어 있었지만, 파이토치는 파이썬으로 작성되어 파이썬의 언어 특징을 많이 가짐
- 즉, Lua 기반의 토치 프레임워크로 페이스북 주도로 여러 회사와 대학이 함께 개발한 오픈소스 소프트웨어
- OOP 스타일로서 파이썬을 파이썬 답게 쓸 수 있게 함

## Define and Run vs Define by Run

- 텐서플로와 파이토치는 둘 다 연산에 GPU를 이용하는 프레임워크
- 텐서플로는 연산 그래프를 먼저 만들고 실제 연산할 때 값을 전달하여 결과를 얻는 'Define and Run' 방식
  - 그래프를 먼저 정의하고 세션에서 실제로 값을 집어넣어 결과를 도출
  - 비직관적
  - 그래프를 정의하는 부분과 이를 돌리는 부분이 분리되기 떄문에 전체적으로 코드 길이가 길어짐
- 파이토치는 그래프를 만듦과 동시에 할당되는 'Define by Run'방식
  - 연산 그래프를 정의하는 것과 동시에 갑솓 초기화되어 연산이 이루어지는 'Define by Run'
  - 연산 그래프와 연산을 분리해서 생각할 필요가 없다.

### Define and Run

- TensorFlow, Caffe, torch, nn, and Theano-based frameworks

### Define by Run

- Chainer, PyTorch

## 파이토치의 가시성

### 파이토치

- 눈에 잘보이도록 하는 것으로 파이썬과 넘파이를 알고있다면 쉽게 적응하고 사용이 가능
- Dynamic computational graph
  - 실행 중에 그래프 변경이 가능
  - 데이터에 실시간으로 대응하는 동적인 학습 방법

### 텐서플로우
- 구글 서비스 엔지니어링을 위해 만들어 졌기 때문에 어려운 느낌
- Static computational graph
  - 정적 계산 그래프
  - 변수들이 지나가는 길인 그래프를 미리 정해주고 실행 중에 바꿀수 없음
  - c언어와 비슷함
  - 최적화 하기 쉽지만 파이썬과 성격이 조금 다름

## Numpy와 PyTorch

- Numpy 배열: 더 빠른 수학 연산을 지원하도록 설계된 numpy 패키지의 핵심 기능
- 데이터 전처리에 사용되는 pandas와 같은 라이브러리는 numpy 배열을 중심으로 구축
- PyTorch 텐서는 numpy 배열과 유사하지만 CUDA지원 Nvidia GPU에서도 작동
- Numpy 배열은 주로 일반적인 기계 학습 알고리즘(scikit-learn의 k-means 또는 Decision Tree)에 사용되는 반면, pytorch 텐서는 딥한 행렬 계산이 필요한 딥러닝에 주로 사용
- numpy 배열과 달리 pytorch 텐서는 deivce_type(계산이 CPU에서 발생하는지 GPU에서 발생하는지 여부) 및 requires_grad(도함수를 계산하는데 사용됨)라는 두 개의 다른 인수를 추가 사용


```python3
array1 = np.array([1, 2, 3, 4])
list1 = [[1, 2, 3, 4], [5, 6, 7, 8]]
array2 = np.array(list1)
array3 = np.array([1, 2, 3, 4], dtype=np.float64)
type(array1), array1.dtype
# (numpy.ndarray, dtype('int64'))
```


```python3
tensor1 = torch.tensor([1, 2, 34])
numpy_arr1 = np.array([11, 21, 322])
tensor2 = torch.tensor(numpy_arr1)
type(tensor1), tensor1.dtype
# (torch.Tensor, torch.int64)
```


```python3
torch.rand(2, 3) # pythorch way
np.random.rand(2, 3) # numpy way
```

#### 재현성을 보장하기 위해 seed 기능을 사용

```python3
np.random.seed(133)
torch.manual_seed(123) # for both CPU and CUDA
```

## Numpy와 Pytorch - Reshaping the array

In [ ]:
import numpy as np
import torch

In [ ]:
np_arr3 = np.random.randint(100, size=(3, 5))

In [ ]:
np_arr3

array([[16, 19, 57, 66, 68],
       [ 0, 28,  5, 14, 22],
       [85, 88, 68, 75, 19]])

In [ ]:
np_arr3.reshape(1, -1)

array([[16, 19, 57, 66, 68,  0, 28,  5, 14, 22, 85, 88, 68, 75, 19]])

In [ ]:
np_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
new_arr = np_arr.reshape(2, 2, -1)

In [ ]:
np_arr.reshape(2, -1, -1)

ValueError: ignored

In [ ]:
tensor1 = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
tensor1.reshape(2, 2, -1)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [ ]:
x = torch.randn(2, 5)

In [ ]:
x

tensor([[ 0.9321, -0.2869,  1.1985, -0.2102,  0.8424],
        [ 1.4058, -0.0882,  0.9620, -1.4622,  1.1667]])

In [ ]:
x.permute(1, 0)

tensor([[ 0.9321,  1.4058],
        [-0.2869, -0.0882],
        [ 1.1985,  0.9620],
        [-0.2102, -1.4622],
        [ 0.8424,  1.1667]])

In [ ]:
x.reshape(5, 2)

tensor([[ 0.9321, -0.2869],
        [ 1.1985, -0.2102],
        [ 0.8424,  1.4058],
        [-0.0882,  0.9620],
        [-1.4622,  1.1667]])

## Numpy와 Pytorch - Add a new dimension

In [ ]:
x = np.random.rand(2, 3)

In [ ]:
np.expand_dims(x, axis=0).shape

(1, 2, 3)

In [ ]:
y = torch.rand(2, 3)

In [ ]:
y.unsqueeze(0).shape

torch.Size([1, 2, 3])