In [ ]:
import torch

In [ ]:
1 # scalar
[1, 2, 3] # vector
[[1, 2, 3]] # metrics
[[[1, 2, 3]]] # n-rank tensor

[[[1, 2, 3]]]

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
print(x.size())

torch.Size([3, 3])


In [ ]:
print(x.shape)

torch.Size([3, 3])


In [ ]:
print(x.ndim)
print(x.ndimension())

2
2


In [ ]:
x = torch.unsqueeze(x, 0)
print(x)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [ ]:
print(x.ndim)

3


In [ ]:
print(x.size())

torch.Size([1, 3, 3])


In [ ]:
x = torch.squeeze(x)
print(x)
print(x.size())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])


In [ ]:
x = x.view(9)
print(x)
print(x.ndim)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
1


In [ ]:
try:
  x = x.view(2, 4)
except Exception as e:
  print(e)

shape '[2, 4]' is invalid for input of size 9


In [ ]:
arr1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
arr2 = torch.tensor([[1, 2,], [3, 4,], [5, 6,]])
print(arr1)
print(arr2)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
w = torch.randn(5, 3, dtype=torch.float)
x = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
print(w.size())
print(x.size())
print(w)
print(x)

torch.Size([5, 3])
torch.Size([3, 2])
tensor([[-0.5321, -0.1493, -1.0508],
        [ 2.3886, -0.5097,  0.8909],
        [ 0.6866,  0.5599,  0.9867],
        [ 0.1339,  1.7407, -0.7358],
        [ 0.5811, -0.6958, -0.6465]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [ ]:
b = torch.randn(5, 2, dtype=float)
print(b)
print(b.size())

tensor([[ 0.2959,  0.6502],
        [-0.8031, -2.0081],
        [-0.0379,  1.0629],
        [ 0.5122,  0.0367],
        [ 1.8933, -0.2480]], dtype=torch.float64)
torch.Size([5, 2])


In [ ]:
wx = torch.mm(w, x)

In [ ]:
print(wx)
print(wx.size())

tensor([[-6.2341, -7.9663],
        [ 5.3139,  8.0837],
        [ 7.3000,  9.5332],
        [ 1.6768,  2.8156],
        [-4.7389, -5.5002]])
torch.Size([5, 2])


In [ ]:
result = wx + b

print(result)
print(result.size())

tensor([[-5.9382, -7.3161],
        [ 4.5108,  6.0756],
        [ 7.2621, 10.5961],
        [ 2.1891,  2.8523],
        [-2.8456, -5.7482]], dtype=torch.float64)
torch.Size([5, 2])


In [ ]:
w = torch.tensor(1.0, requires_grad=True)
a = w * 3

In [ ]:
l = a**2

In [ ]:
# l = a^2 = (3w)^2 = 9w^2
l.backward()
print(w.grad)

tensor(18.)
